In [12]:
# 2张照片，照片尺寸是3*4像素。
# 0维 -> 照片
# 1维 -> 行
# 2维 -> 列
# 对行求均值，3行合并成1行。
# 对2*4 求均值，4列合并成1列。
from numpy import *
a = arange(24).reshape(2, 3, 4)
print(a)
a = a.mean(1)
print("="*20)
print(a)
print("="*20)
print(a.shape)
a=a.mean(1)
print(a)
print(a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[  4.   5.   6.   7.]
 [ 16.  17.  18.  19.]]
(2, 4)
[  5.5  17.5]
(2,)


In [9]:
x = [1, 4, 7]
y = [2, 5, 8]
print(zip(x, y))

[(1, 2), (4, 5), (7, 8)]


<type 'numpy.ndarray'>
